language: python

python:
  - "2.7"
  # - "3.3" # Too many problems with setuptools compatibility, try distutils instead?
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

services:
  - docker

env:
  global:
    # Environment Variables - Travis CI
    - PYPI_USERNAME=achillesrasquinha
    - DOCKER_HUB_USERNAME=achillesrasquinha

    # Environment Variables - Makefile
    - ENVIRONMENT=test
    - VERBOSE=true
    - secure: VJs9MZAeYdBXxE1ePMe9UT7weaj6phvTisSk/Esz6/9QOeTUSdsMW/NuWce2DRagqa0glKc4Eur4bRBLNcx7xQ4uHmKsEOCu86GOumuZ4Z3g0zPqEf+SoCMczURjD+XsIvs5V7agoA1M0FCOWl6WfCEMRoFExfFdI8BCz6F0EYV/6Z5PYrEsuVxsDpF/hVoDzrtMO1lRKUVg3utf1HDYGuch613sjI7GU3sKKQpb9eR/4pUgQwfEgcPDfsqgYcJ4+JTPqrcBz8P5S/XJEfOXGg/B9MpZVccQj/hWHHXPEiAJNfGLsP1iTmhbYF4cGrEMxmmuXL5Y2Q0IvDb5Sp1OKS580eFkcbjWQupXqKEOZk//5ac8GdxjrDZSIilZRS2Even9O4FnzAvWnY+7tEbn47PMintxhI5IryxC/mJ66cOmhBgzBCESqxGIw0dOZdMDsrMlnLQV8V+RYpLs9udNU/skzbBCnyZzGp7+0kcCS8l2U6CSbpkUHYbSTNmbveFpDmS98n0tUL+m01qGY+UmQFXcbXq8NbKYMX227XYKmCK0GU1z3SRWfaX99xmJG+tgCWrD+VihBvBv+cuXTl1u32/UBmEhrm2AZM+Hz9m/9D4IGa58l+KjxVVd2Qxqq1MWRRK55wazbWiCR77WAlDXiZxFpVwZrqalJ3S0DtmrS5I=

install:
  - sudo $TRAVIS_BUILD_DIR/ci/scripts/bash/install.sh
  - make install

script:
  - make test docker-build

after_success:
  - $TRAVIS_BUILD_DIR/ci/scripts/bash/release.sh

deploy:
  - provider: pypi
    user: $PYPI_USERNAME
    password:
      secure: DxyaBiRgMiAZDshCiERWpg/CEtGzqNDvBJPNUPWmapxkpsWFx/n9gLqJW9774q0GmcPim15HvwJ9Wu6QRmsKAZ2lAXb7dxU1UcJh2YJVZvnJFiUg4ycil9eSxyhIz6RwHzKVzHCbzHgxyVhVvdEKaeLqy7FojEbJ4EUyJnp1+0i2SEP0t1urM5yShosHyYX9wkXTsUJ2NnwM5onboJZq3WYLyPfSXLdk9ylbvh0cRiuMZl5irxBsdrz0pxQXiDWjfti93qToe6CisNUO5ImdBZAB4/sbG510CUoQHY1/AGSzysPNp88PMK4jrfNRwlKkopTOLswnfoJO7rmTsbB2R2CoBq7CpQW/GgsOwdHPODwOC9ionROYHBrNmeAWKtDlXZL757qZnCHRYP4CXBKPcDVZfpae25eezrwaISYKDlV3HDUaLODv0GqmvVNQaABrMt7kZ9zPDP0M7aXR/n+YFYkjQgW8LJUtWxhNrYXPmX+oNJA6os1Pet0w9iT+oC4QeYpTojO9dKuvFSglFuSqwVVbeK5CSKlsA5OBDgsYFK4PZK4+JxV+jnZ/Fb6AjEj7/4FR/bAeO/hkNfqmUsOLOKRp09soyJRtx0qw7BSwe9rEA7pL7TCa5aB0RAEDwYiNuf+JRe9sPUEE7fhcqA2zM7YP+sHpfgzm59ouDh4XLME=
    on:
      tags: true
    skip_existing: true
  - provider: script
    script: $TRAVIS_BUILD_DIR/ci/scripts/bash/docker-deploy.sh
    on:
      branch: master